A = read.table ("A.txt")
C = read.table ("C.txt")
D = read.table ("D.txt")
E = read.table ("E.txt")
F = read.table ("F.txt")
M = read.table ("M.txt")
N = read.table ("N.txt")
G = read.table ("G.txt")
H = read.table ("H.txt")
I = read.table ("I.txt")
K = read.table ("K.txt")
L = read.table ("L.txt")
P = read.table ("P.txt")
Q = read.table ("Q.txt")
R = read.table ("R.txt")
S = read.table ("S.txt")
T = read.table ("T.txt")
V = read.table ("V.txt")
Y = read.table ("Y.txt")
W = read.table ("W.txt")
pdf ("AA_FREQ.pdf")
par (mfrow=c(4,5))
plot (colMeans(A), type="l")
plot (colMeans(C), type="l")
plot (colMeans(D), type="l")
plot (colMeans(E), type="l")
plot (colMeans(F), type="l")
plot (colMeans(M), type="l")
plot (colMeans(N), type="l")
plot (colMeans(G), type="l")
plot (colMeans(H), type="l")
plot (colMeans(I), type="l")
plot (colMeans(K), type="l")
plot (colMeans(L), type="l")
plot (colMeans(P), type="l")
plot (colMeans(Q), type="l")
plot (colMeans(R), type="l")
plot (colMeans(S), type="l")
plot (colMeans(T), type="l")
plot (colMeans(V), type="l")
plot (colMeans(Y), type="l")
plot (colMeans(W), type="l")
dev.off()
s_A = log2(sum (colMeans(A)[1:29])/ sum(colMeans(A)[30:57]))
s_C = log2(sum (colMeans(C)[1:29])/ sum(colMeans(C)[30:57]))
s_D = log2(sum (colMeans(D)[1:29])/ sum(colMeans(D)[30:57]))
s_E = log2(sum (colMeans(E)[1:29])/ sum(colMeans(E)[30:57]))
s_F = log2(sum (colMeans(F)[1:29])/ sum(colMeans(F)[30:57]))
s_M = log2(sum (colMeans(M)[1:29])/ sum(colMeans(M)[30:57]))
s_N = log2(sum (colMeans(N)[1:29])/ sum(colMeans(N)[30:57]))
s_G = log2(sum (colMeans(G)[1:29])/ sum(colMeans(G)[30:57]))
s_H = log2(sum (colMeans(H)[1:29])/ sum(colMeans(H)[30:57]))
s_I = log2(sum (colMeans(I)[1:29])/ sum(colMeans(I)[30:57]))
s_K = log2(sum (colMeans(K)[1:29])/ sum(colMeans(K)[30:57]))
s_L = log2(sum (colMeans(L)[1:29])/ sum(colMeans(L)[30:57]))
s_P = log2(sum (colMeans(P)[1:29])/ sum(colMeans(P)[30:57]))
s_Q = log2(sum (colMeans(Q)[1:29])/ sum(colMeans(Q)[30:57]))
s_R = log2(sum (colMeans(R)[1:29])/ sum(colMeans(R)[30:57]))
s_S = log2(sum (colMeans(S)[1:29])/ sum(colMeans(S)[30:57]))
s_T = log2(sum (colMeans(T)[1:29])/ sum(colMeans(T)[30:57]))
s_V = log2(sum (colMeans(V)[1:29])/ sum(colMeans(V)[30:57]))
s_Y = log2(sum (colMeans(Y)[1:29])/ sum(colMeans(Y)[30:57]))
s_W = log2(sum (colMeans(W)[1:29])/ sum(colMeans(W)[30:57]))
data= data.frame (aa = c("A","C","D","E","F","M","N","G","H","I","K","L","P","Q","R","S","T","V","Y","W") , score = c(s_A,s_C,s_D,s_E,s_F,s_M,s_N,s_G,s_H,s_I,s_K,s_L,s_P,s_Q,s_R,s_S,s_T,s_V,s_Y,s_W) )
data = data [ order (data$score),]
pdf ("UPS_DOWN_RATIO.pdf")
par (mfrow=c(1,2))
barplot (data$score, names.arg= data$aa , horiz=TRUE, xlim=c(-0.2,0.9))

bumps = read.table ("_ONLY_AWAY_DETAILED.bed")

bumps$mid = round (bumps$V2 + ((bumps$V3-bumps$V2)/2) )
cds = read.table ("CDS.bed")
colnames (cds) = c("V1","CS","CE")
bumps_cds=  merge (bumps, cds, by="V1")
bumps_cds$aa_mid = round ((bumps_cds$mid - bumps_cds$CS)/3) +1
bumps_cds_atleast30= bumps_cds[ bumps_cds$aa_mid >= 30,]
bumps_cds$aa_length= round ((bumps_cds$CE - bumps_cds$CS)/3) 
bumps_cds_atleast30= bumps_cds[ bumps_cds$aa_mid >= 30 & ( (bumps_cds$aa_length - bumps_cds$aa_mid) > 30),]

write.table (bumps_cds_atleast30, "bumps_cds_atleast30.txt",sep="\t", quote=FALSE, row.names=FALSE)
#quit()


########################################################################################################################################

library(dplyr)

dfA <- as.data.frame(colMeans(A))
dfC <- as.data.frame(colMeans(C))
dfD <- as.data.frame(colMeans(D))
dfE <- as.data.frame(colMeans(E))
dfF <- as.data.frame(colMeans(F))
dfM <- as.data.frame(colMeans(M))
dfN <- as.data.frame(colMeans(N))
dfG <- as.data.frame(colMeans(G))
dfH <- as.data.frame(colMeans(H))
dfI <- as.data.frame(colMeans(I))
dfK <- as.data.frame(colMeans(K))
dfL <- as.data.frame(colMeans(L))
dfP <- as.data.frame(colMeans(P))
dfQ <- as.data.frame(colMeans(Q))
dfR <- as.data.frame(colMeans(R))
dfS <- as.data.frame(colMeans(S))
dfT <- as.data.frame(colMeans(T))
dfV <- as.data.frame(colMeans(V))
dfY <- as.data.frame(colMeans(Y))
dfW <- as.data.frame(colMeans(W))

df_all <- dplyr::bind_cols(dfA, dfC, dfD, dfE, dfF, dfM, dfN, dfG, dfH, dfI, dfK, dfL, dfP, dfQ, dfR, dfS,dfT,dfV,dfY,dfW)

colnames(df_all) <- c("A","C","D","E","F","M","N","G","H","I","K","L","P","Q","R","S","T","V","Y","W") 

df_all$index <- row.names(df_all)

dfall <- df_all[,c(21,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)]

write.table(dfall, "bumpfinderScores.txt", sep = "\t", quote = FALSE)

quit()

